In [14]:
import torch


def load_jit_model(model_path = '/home/aw1223/ip/agile/model.pt'):
    model = torch.jit.load(model_path)
    return model


def load_graph(graph_path = '/home/aw1223/ip/agile/graph.pth'):
    graph = torch.load(graph_path)
    input_data = graph['input_data']
    x_loaded = input_data['x']
    edge_index_loaded = input_data['edge_index']
    return x_loaded,edge_index_loaded


def get_expected_outputs(model, x, edge_index):
    ####Remove bias from the model TODO Add biases####
    state_dict = model.state_dict()
    for name, param in state_dict.items():
        if 'bias' in name:
            # Reset the bias tensor to all zeros
            state_dict[name] = torch.zeros_like(param)

    model.load_state_dict(state_dict)
    ###################################################

    # state_dict = model.state_dict()
    # state_dict['layers.0.bias'] = torch.tensor([0] * state_dict['layers.0.bias'].size()[0])
    # state_dict['layers.1.bias'] = torch.tensor([0] * state_dict['layers.1.bias'].size()[0])
    # # state_dict['layers.2.bias'] = torch.tensor([0] * state_dict['layers.2.bias'].size()[0])
    # # state_dict['layers.3.bias'] = torch.tensor([0] * state_dict['layers.3.bias'].size()[0])

    # model.load_state_dict(state_dict)
    model.eval()
    with torch.no_grad():
        output = model(x, edge_index)
    del model

    return output



def log_model_input(x):
    for idx,input_i in enumerate(x):
        print(f"Input {idx}:")
        print(input_i)
        print('len', len(input_i))
        print("\n")


In [15]:

model = load_jit_model()
x, edge_index = load_graph('/home/aw1223/ip/agile/graph.pth')
print(edge_index)

output = get_expected_outputs(model, x, edge_index)


tensor([[ 0,  0,  1,  1,  1,  1,  2,  2,  3,  4,  4,  4,  4,  5,  8,  8,  9,  9,
         10, 10, 11, 11, 11, 11, 11, 12, 12, 13, 13, 14, 15, 15, 15, 16, 17, 17,
         18, 18, 18, 18, 20, 21, 21, 21, 21, 22, 24, 24, 24, 25, 25, 25, 26, 26,
         27, 28, 28, 28, 29, 29, 30, 30, 31, 32, 32, 32, 33, 33, 34, 34, 35, 35,
         36, 36, 37, 38, 39, 39, 39, 39, 39, 40, 41, 42, 42, 43, 43, 44, 44, 44,
         45, 45, 45, 46, 46, 46, 47, 47, 47, 47, 48, 49, 49, 49, 49, 50, 51, 51,
         52, 53, 53, 53, 54, 54, 54, 55, 55, 56, 57, 58, 59, 60, 60, 61, 62, 62,
         62, 63, 63, 63, 64, 64, 64, 65, 66, 66, 66, 66, 67, 67, 67, 68, 69, 70,
         71, 72, 72, 72, 73, 73, 73, 74, 74, 76, 76, 76, 77, 77, 77, 77, 78, 78,
         80, 80, 81, 81, 81, 82, 84, 84, 85, 86, 86, 86, 87, 88, 88, 88],
        [15, 52, 39, 49, 51, 53, 53, 85, 58, 30, 42, 47, 60, 80, 35, 51, 47, 86,
         39, 44, 13, 54, 62, 82, 86, 18, 74, 11, 26, 55,  0, 30, 34, 55, 21, 61,
         12, 46, 47, 64, 71, 17, 57

In [16]:

log_model_input(x)

for layer_idx, data in enumerate(output):
    print(f"Layer {layer_idx+1}")
    for idx,node in enumerate(data):
      print('Node',idx)
      print(node)
      print(len(node))



Input 0:
tensor([-1.5064, -1.6152,  0.2073,  0.4436, -0.8757, -1.5909, -1.3982, -0.2682,
        -0.8312, -0.8794,  1.9864,  0.3755,  1.7686,  0.3611,  1.9537,  0.1912,
        -1.3967,  0.0082,  0.8705, -1.4419,  0.3947, -1.5968, -1.3380, -0.2532,
         1.0177,  0.0729,  1.2761, -1.4360, -0.1118,  1.9346, -1.2476, -1.3940,
         1.5571,  0.9124])
len 34


Input 1:
tensor([-0.0310, -0.5537, -1.7086,  1.8976, -0.9549, -1.4307, -1.2273,  1.2419,
         0.7073, -0.1100,  1.2112,  1.7339,  0.6442,  0.1617, -1.1873,  1.4686,
        -0.7667,  1.8192,  0.0152, -1.2866,  0.1775, -1.7713,  0.3587,  0.5031,
         0.8723, -1.3699,  1.5058,  1.1024, -1.8091, -1.5608, -0.6521,  1.8544,
         0.5986,  0.2725])
len 34


Input 2:
tensor([-1.9015,  1.0941,  0.9576, -1.2795, -1.7383, -0.9168,  1.7796,  0.1720,
        -0.3353,  0.2357,  1.6397,  1.3767, -0.6110,  1.3134,  0.6569, -1.7170,
        -0.4498, -1.3293, -0.1247, -1.6824, -0.7182,  0.1200,  0.7329, -1.4780,
        -1.2463, -0.6